### ISSUE TITLE
Suspected database file isn't configured

### ISSUE THREAD

**Issue by attuploadsuser** [Ziconius/FudgeC2#6]
**Describe the bug**
Traceback (most recent call last):
  File "Controller.py", line 14, in <module>
    from ServerApp import ImplantManager
  File "/Users/2on5/Desktop/FudgeC2/FudgeC2/ServerApp/ImplantManager.py", line 9, in <module>
    from ServerApp.modules.UserManagement import UserManagementController
  File "/Users/2on5/Desktop/FudgeC2/FudgeC2/ServerApp/modules/UserManagement.py", line 4, in <module>
    from email_client.email_notifications import EmailNotification
  File "/Users/2on5/Desktop/FudgeC2/FudgeC2/email_client/email_notifications.py", line 16, in <module>
    ec = EmailClient()
  File "/Users/2on5/Desktop/FudgeC2/FudgeC2/email_client/email_client.py", line 28, in __init__
    host=data['host'],
TypeError: string indices must be integers

print(data)==>No email configuration exists

**Comment by Ziconius** [comment]
Hey,

Did you upgrade from 0.5.7 and are you using a 0.5.7 database?

F2 definitely should have gracefully failed here - I've got work on to upgrade DB schemas during upgrades, and I'll review data types. 

Thanks for the report!

**Comment by Ziconius** [comment]
Working on this fix in #8. Closing here.
